name: '🐛 Bug report'
description: Report a bug/problem
title: '<title>'
labels: ['🐛 bug', '👀 needs triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: package
    validations:
      required: true
    attributes:
      label: Affected package
      description: Which package is affected?
      options:
        - Core
        - Components
        - Docs

  - type: textarea
    id: what-happened
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see and add screenshots if relevant!

  - type: textarea
    id: reproduce-step
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see and add screenshots if relevant!

  - type: textarea
    id: suggested-solution
    validations:
      required: false
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like.

  - type: dropdown
    id: platforms
    validations:
      required: true
    attributes:
      label: What platforms does this bug report apply to?
      description: You may select more than one.
      multiple: true
      options:
        - Desktop
        - Mobile
        - Tablet
        - TV
        - Foldable

  - type: dropdown
    id: browsers
    validations:
      required: true
    attributes:
      label: What browsers are you seeing the problem on?
      description: You may select more than one.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Opera
        - Other (add additional context)

  - type: input
    id: context
    validations:
      required: false
    attributes:
      label: Additional context
      description: Add any other context about the problem or helpful links here.
