blank_issues_enabled: true
contact_links:
  - name: ❓ Start a discussion
    url: https://github.com/ATOS-DESIGN/.github/discussions
    about: Start a discussion or ask questions about the Atos Design System
