name: '🤷 Other'
description: Everything that doesn't fit in the other categories
labels: ['👀 triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!

  - type: dropdown
    id: package
    validations:
      required: false
    attributes:
      label: Affected package
      description: Which package is affected?
      options:
        - Core
        - Components
        - Icons
        - Docs
        - Bootstrap

  - type: dropdown
    validations:
      required: false
    attributes:
      multiple: true
      label: What area is affected?
      options:
        - '♿ Accessibility'
        - '🤖 Build'
        - '🔁 CI/CD'
        - '📦 Components'
        - '📄 Documentation'
        - '🔥 Performance'
        - '🔐 Security'
        - '🎨 Styles'
        - '✅ Tests'
        - '🤷 Other'

  - type: textarea
    id: suggested-solution
    validations:
      required: true
    attributes:
      label: Desciption
      description: Describe what you'd like to change.

  - type: input
    id: context
    validations:
      required: false
    attributes:
      label: Additional context
      description: Add any other context about the problem or helpful links here.
