name: Sync labels
on:
  # Allows you to call this workflow from other workflows
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Schedule this to run every 24 hours
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  labels:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/eviden-parallel/.github/main/.github/labels.yml
          delete-other-labels: true
