# This is the workflow to lint the source code
name: Lint Code

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: '🕵️‍♂️ Lint Code'
    runs-on: ubuntu-latest
    # container: node:lts-bullseye

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: '⚙️ Use Node.js'
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@atos-parallel'

      - name: '⛓️ Install dependencies'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: '✅ Lint code'
        run: npm run lint
