# This is workflow runs on PR
#
name: Pull request

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request_target:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: PRT_${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-pr:
    name: '📌'
    uses: ./.github/workflows/lint-pr.yml

  lint-code:
    name: '📌'
    needs: [lint-pr]
    uses: ./.github/workflows/lint-code.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}

  dependabot:
    name: '📌'
    uses: ./.github/workflows/dependabot.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN  }}
