# This is workflow runs on PR
#
name: Pull request

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request_target:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-pr:
    name: '▶️ actions'
    uses: ATOS-DESIGN/actions/.github/workflows/lint-pr.yml@v1

  lint-code:
    name: '▶️ actions'
    needs: [lint-pr]
    uses: ATOS-DESIGN/actions/.github/workflows/lint-code.yml@v1
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}

  dependabot:
    name: '▶️ actions'
    uses: ATOS-DESIGN/actions/.github/workflows/dependabot.yml@v1
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN  }}
