# This is workflow runs on push
#
name: Push

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-code:
    name: '▶️ actions'
    uses: ATOS-DESIGN/actions/.github/workflows/lint-code.yml@v1
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
