name: 'Release'

on:
  # Continuous release on push in the following branches
  push:
    branches:
      - main
      - next
      - beta
      - alpha

  # Manual Release
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    name: '🏷️ Release'
    needs: [validate]
    runs-on: [self-hosted, linux]
    container: node:lts-bullseye
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ steps.release.outputs.version }}

    permissions:
      contents: write
      packages: write

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: '⚙️ Use Node.js'
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@atos-design'

      - name: '➡️ Configure NPM Proxy'
        uses: de-als-cycos-dev/actions-npm-proxy@v1

      - name: '⛓️ Install dependencies'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: '🛠️ Build'
        run: npm run build

      - name: '📦 Release'
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0 # disable pre-commit hooks
        run: |
          npm run release
          echo "::set-output name=version::$(npm run env | grep npm_package_version | cut -d '=' -f 2)"

      - name: '🧹 Cleanup workspace'
        uses: ATOS-Actions/clean-self-hosted-runner@v1
