name: Validate

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events
  pull_request_target:
    types: [opened, synchronize, reopened]

  # Allows you to call this workflow from other workflows
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: '🕵️‍♂️ Lint'
    runs-on: [self-hosted, linux]
    container: node:lts-bullseye

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: '⚙️ Use Node.js'
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'

      - name: '➡️ Configure NPM Proxy'
        uses: de-als-cycos-dev/actions-npm-proxy@v1

      - name: '⛓️ Install dependencies'
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: '✅ Lint code'
        run: npm run lint

      - name: '🧹 Cleanup workspace'
        uses: ATOS-Actions/clean-self-hosted-runner@v1
